let oi = true;
let tchau = false;
let armazenar = oi && tchau;
console.log(armazenar);
let tarefa = true;
let trabalho = false;
let armazenar2 = tarefa || trabalho;
console.log(armazenar2);
console.log(!armazenar);
console.log(!armazenar2);
